### ISSUE TITLE
Issue installing with no build.xml

### ISSUE THREAD

**Issue by TomReinhart-Salesforce** [doctales/org.doctales.schematron#4]
Hi I had success installing this last week but since the removal of build.xml I'm unable to install using the same command $dita --install https://github.com/doctales/org.doctales.schematron/archive/master.zip Do you have a fix for how you want to install this now? dita-ot-3.0.4/plugins/org.doctales.schematron/build.xml (No such file or directory)

**Comment by xephon2** [comment]
@TomReinhart-Salesforce, sorry!
