### ISSUE TITLE
list only files that match a validation criteria in schematron.log file

### ISSUE THREAD

**Issue by ULMethner** [doctales/org.doctales.schematron#7]

**Comment by xephon2** [comment]
Could you please test with develop?

**Comment by ULMethner** [comment]
[MSI.schematron.log](https://github.com/doctales/org.doctales.schematron/files/4375113/MSI.schematron.log)

I integrated the plugin and got the results in the attached file. Thank you

**Comment by xephon2** [comment]
Ok, you have not tested with develop. No problem, I'll create a new release soon. Then it should work as you expect it.

**Comment by xephon2** [comment]
Please try again now.

**Comment by ULMethner** [comment]
It looks like it is working well. Thank you
